### ISSUE TITLE
Fix credit, copyright and License

### ISSUE THREAD

**Issue by mcanevet** [codejamninja/volback#1]
This project is a fork of Bivac, a Camptocamp project, under Apache 2.0 license. Can you please fix the copyright, add license back to Apache 2.0, and credit Camptocamp for its work?

**Comment by raphink** [comment]
Also, @cryptobioz and I mostly drink tea, not coffee :wink:

**Comment by codejamninja** [comment]
If you could explain what needs fixed that would be great. I went through the license carefully and everything seems compliant. Absolutely great work btw!

**Comment by mcanevet** [comment]
Please read carefully also https://en.wikipedia.org/wiki/Software_relicensing. Especially this part : "For successful relicensing the agreement of all involved copyright holders, typically the developers, to a changed license is required. While in the free and open-source domain achieving 100% coverage of all authors is often impossible due to the many contributors involved, often it is assumed that a great majority is sufficient.".

**Comment by raphink** [comment]
@codejamninja 

I understand that under the Apache 2.0 license, you are technically allowed to copy the libraries from the Bivac project, add a copyright/license notice as a header to each of the files, and relicense the whole project under MIT.

However, I hope you understand that while it could be seen as somewhat flattering that our code would be worth such a process, it came as rather shocking to us to realize that the whole project was simply cloned and force-pushed into another project name, without a clear historical link (since you didn't fork), and that the README makes no mention whatsoever of our work. In fact, it claims you are the sole author, and even the list of commits to the project would seem to indicate you wrote most of it, since it counts commits to your `archived` branch, which has nothing do with Bivac.

As I was researching the project, I saw you have a `volback-api` repository, which seems quite interesting.

Besides legal issues, we would have thought it fair and constructive (although not legally mandatory) to share your intentions with us, as we believe the additions you are making are quite interesting.

This kind of events, which I believe is not intentional, is what makes some people say Open-Source is flawed as an intellectual property model. Again, it could be that we are at fault for choosing a very permissive license without measuring the possible repercussion (and in that case, it might just encourage us to switch our projects back to GPLv3 to avoid such situations in the future). I guess we just hoped open-source contributors had the habit of communicating their intent before forking projects entirely.

I hope you understand, and that we can have a fruitful collaboration.

**Comment by codejamninja** [comment]
You thought your response was long 😂

There is a tricky balance between contributing to a project versus forking a project and taking it in a new direction. I have contributed to hundreds of open source projects and almost always contribute with a pull request. The reasons are pretty straightforward.

#1 A community is already using the project
#2 It’s a burden to take on the responsibility of maintaining a project
#3 It’s more valuable to share work as opposed to taking projects in two different directions (there’s just more bandwidth)
#4 It’s just plain ole polite

However those advantages come at a cost (assuming it’s not your own project)
#1 you’re dependent on others accepting your work
#2 the development lifecycle is slower (for your own features)
#3 you have less control in the direction of the project

In most cases the advantages of pull requests far outweigh the alternative for obvious reasons, such as not having to maintain the project and having the advantage of getting awesome new features from future contributions.

However, there are a few cases where I choose to fully fork and maintain a project instead of contributing back. They are for one or many of the following reasons.
#1 I need the feature really bad and don’t have time to wait and wonder if my pull requests will get accepted 
#2 The original project development is not active (aka the team is dead)
#3 My pull requests are ghosted
#4 I have different plans than the original teams plans

A good example of this is recommonmark, a markdown parser for sphinx. The project did not support markdown tables. I wrote a pull request to support tables which required using a different markdown engine. My pull requests were originally ghosted, but the for understandable reasons they were rejected (aka they didn’t want to switch markdown engines).

I ended up forking their project and created sphinx-markdown-parser

https://github.com/rtfd/recommonmark
https://github.com/codejamninja/sphinx-markdown-parser

In the case of bivac, the reason for forking the project is a combination of #1 and #4. I’ve been working on volback for several years (granted I got busy with other things and the project became stagnated). However when I finally got back to it, I discovered your codebase and found several things about it that were superior to my original approach. I thought about contributing, but after discovering that you were not interested in restore logic (plus a ton of features I am planning on), I decided to fork it so I could iterate quickly and take it in the direction I want. The reason I merged my old python code in was because I never delete code.

Ok, with that out of the way, I’m actually really pleased that you are reaching out, because I would be more than willing (in fact would be thrilled) to move my development back to bivac. However, the motivations for forking the project in the first place would need to be solved to a reasonable extent. I do believe that it would be mutually beneficial.

So, again #1 and #4 were the primary reasons for forking he project. #1 would be solved to a satisfactory level if you let me join the project (obviously standard procedures will be followed . . . I’m not going to just blow away your code or start dumping new features in without consensus. However I would like more flexibility than just forking and making pull requests in the dark. I have read through every line of code dozens of times and understand the architecture. (It would have been impossible to write he restore logic without understanding the pipeline end to end).

#4 would be solved if you let me go over my original plans for volback. Obviously it doesn’t need to perfectly match them, but I would like the freedom to move the project in that direction to some extent. So basically end game for volback is the following . . .
#1 backup and restore volumes
#2 support database dumps and restores
#3 compatible with kubernetes
#4 detailed user friendly high level api (with authentication) for managing backups
#5 slick web UI for managing backups
#6 ability to upload and move around snapshots (this will make it easy to migrate projects)
#7 high level functionality for migrating projects across platforms

So, thanks for taking your time to read this. My goal is not to rip off someone else’s work, but I’m not going to reinvent the wheel when I don’t have to. Oh, and one more thing, (this is super insignificant), I like the name volback better than the name bivac. Volback is a self explainable name.

**Comment by codejamninja** [comment]
Hopefully this comment won’t matter but I just feel like mentioning it. Based on your license, the developer is called camptocamp. If you want individual (human) developers to be required to be mentioned, then you need to add them to your license as developers. I would actually be breaking your license conditions if I mentioned them in the license because I’m not allowed to modify it.

However, that said, out of courtesy I have no problem referencing the developers.

Again, this may be a mute point if we join forces.

**Comment by raphink** [comment]
Thanks for your answer.

I'm pleased to hear your approach and your reasons for forking. While we have not been interested in implementing restore ourselves, I don't think we pushed it out of the scope of what we would be willing to accept in Bivac. Besides that, I don't really see anything that shocks me in your goals. Just wondering if maybe the UI could be developed as a separate repository, but that's a detail in a way.

Names… that's always the hardest part of software projects, isn't it? Bivac was actually initially named "Conplicity" because it was based on duplicity. There's been a whole issue over this: https://github.com/camptocamp/bivac/issues/88

As far as I'm concerned, I wouldn't see a problem in welcoming external contributors to this project. There's a gitter room where we can discuss and collaborate (until we move it to Slack, maybe…).

**Comment by codejamninja** [comment]
Ok, sounds good. I’ll turn this into a pull request. And yes, I’m going to build the high level api as a separate project as well. Loopback 4 has a very nice abstraction called repositories that will make it easy to wrap around the bivac cli.
